algoritmo "OperacaesBASICAS"

var
opcao : inteiro


funcao f_soma (n_p1, n_p2: inteiro): inteiro
var
soma, n1, n2: inteiro
inicio
escreval("Informe o primeiro número:")
leia(n1)
escreval("Informe o segundo número:")
leia(n2)
ecsreval("O resultado da soma é =" n1 + n2)
retorne soma
fimfuncao


funcao f_subtracao
var
inicio

fimfuncao


funcao f_divisao
var
inicio

fimfuncao


funcao f_multiplicacao
var
inicio

fimfuncao