algoritmo "ImparesPares/Primo"

var
opcao : inteiro


funcao
var
inicio

fimfuncao


funcao
var

inicio

fimfuncao


inicio
enquanto opcao <> 9 faca
   escreval("Informe a operacao desejada")
   escreval("1-Números Primos")
   escreval("2-Pares e Impares")
   escreval("9-Sair")
   leia(opcao)
   escolha(opcao)
   caso 1

   caso 2

   caso 9
      escreval("Finalizado com sucesso")
   fimescolha
fimenquanto
fimalgoritmo
